v7.0.0 (#186)
**Complete rewrite using [nushell](https://nushell.sh) - see UPGRADE_FROM_6x_TO_7x.md**

## Major updates and breaking changes
* To enter nushell do `docker exec -it container_name nu` and type `bf-mariadb + tab` to see a complete list of functions
* Changing VOL mount points to `/data` and `/backup`
* All environment variables now begin `BF_DB`

## Minor updates
* Updating to MariaDB 10.5.26, 10.6.19, 10.11.9, 11.1.6, 11.2.5
* Adding MariaDB 11.4.3, 11.5.2 and 11.6.1
* Dropping MariaDB 10.4.x, 10.9.x, 10.10.x and 11.0.x (out of support)
* Improving server checks
* Adding executable to enable / disable super user (see README)
* Using expanding APT syntax for MariaDB source list

## Build updates
* Updating workflows to latest versions
* Using -dev instead of -beta for development builds
* Using ghcr.io

## Development updates
* Enforcing LF line endings
* Map port 3306 to enable local connections when testing

## Documentation updates
* Updating copyright year to 2024
* Adding renamed environment variables and new executables

diff --git a/overlay/usr/bin/bf/healthcheck b/overlay/usr/bin/bf/healthcheck
--- a/overlay/usr/bin/bf/healthcheck
+++ b/overlay/usr/bin/bf/healthcheck
@@ -1,20 +1,8 @@
-#!/command/with-contenv bash
+#!/usr/bin/nu
 
-set -euo pipefail
-export BF_E=`basename ${0}`
+use bf
+use bf-mariadb
+bf env load -x
 
-
-#======================================================================================================================
-# Copyright (c) 2015 Thomas Boerger <https://webhippie.de>
-# Originally from https://github.com/dockhippie/mariadb/blob/master/latest/overlay/etc/s6/mariadb/run
-#
-# Modifications copyright (c) 2021 bfren
-#======================================================================================================================
-
-USERNAME=${MARIADB_USERNAME:-root}
-PASSWORD=${MARIADB_PASSWORD:-${MARIADB_ROOT_PASSWORD}}
-
-CHECK="$(echo 'SELECT 1;' | mariadb --host=127.0.0.1 --user=${USERNAME} --password=${PASSWORD} 2>/dev/null | head -n1)"
-
-[[ "${CHECK}" == "1" ]] && exit 0
-exit 1
+# Healthcheck will fail if the server is not online
+export def main [] { if not (bf-mariadb checks server_is_online) { exit 1 } }
